#pragma once

#include "resource.h"

#define MAXCH 32

struct _GMainLoop;
typedef struct _GMainLoop GMainLoop;
extern bool g_onair[32];

class RtspServerController
{
public:
    RTSPCtrl        rCtrl; //GMainLoopを含む 

    RtspServerController();
    ~RtspServerController();

    //bool Start(int inPort, int outPort, const std::string& channelUtf8, HWND hwndNotify);
	bool StartEx(HWND hwndNotify, bool _test_pattern=false); //rCtrlの内容を使う版

    void Stop();
    bool IsRunning() const { return running_.load(); }

private:
#ifdef USE_OLD_VERSION
    void ThreadMain(int inPort, int outPort, std::string channelUtf8);
#endif
	void ThreadMainEx();        //スレッド呼び出しなので、デフォルト変数は使えない
    void ThreadMainExTest();    //スレッド呼び出しなので、デフォルト変数は使えない 処理は同じなんだけどね

    //void ThreadMain(GST_RTSP_SVPARAMS& _gsrv, std::string channelUtf8);
    //void ThreadMainGsrv(GST_RTSP_SVPARAMS& _gsrv);

private:
    std::atomic<bool> running_{ false };
    std::thread       th_;
    //GMainLoop*        loop_{ nullptr };
    HWND              hwndNotify_{ nullptr };

};

std::string WideToUtf8(const std::wstring& ws);
bool GetIntFromEdit(HWND hDlg, int id, int& outValue);
std::vector<std::string> getLocalIPAddresses();
bool SetClipboardTextW(HWND owner, const std::wstring& text);
void FillUrlCombo(HWND hDlg, int combo_id, int out_port, const std::string& channel_name);
void FillUrlCombo_http(
    HWND hDlg,
    int combo_id,
    int http_port,
    int out_port,
    const std::wstring& channel_name,
    const std::wstring& _hls
);
void CopySelectedComboTextToClipboard(HWND hDlg, int combo_id);

//////////////////////////////////////////////////////////////////////////////////////
struct APP_SETTINGS
{
	int size = MAXCH; // チャンネル数
    std::array<std::wstring, MAXCH> SVNAME = {
    L"CH01",L"CH02",L"CH03",L"CH04",L"CH05",L"CH06",L"CH07",L"CH08",
    L"CH09",L"CH10",L"CH11",L"CH12",L"CH13",L"CH14",L"CH15",L"CH16",
    L"CH17",L"CH18",L"CH19",L"CH20",L"CH21",L"CH22",L"CH23",L"CH24",
    L"CH25",L"CH26",L"CH27",L"CH28",L"CH29",L"CH30",L"CH31",L"CH32"
    };

    std::array<UINT, MAXCH> IDC_EDIT_PORTIN = {
        IDC_EDIT_PORTIN1,IDC_EDIT_PORTIN2,IDC_EDIT_PORTIN3,IDC_EDIT_PORTIN4,
        IDC_EDIT_PORTIN5,IDC_EDIT_PORTIN6,IDC_EDIT_PORTIN7,IDC_EDIT_PORTIN8,
        IDC_EDIT_PORTIN9,IDC_EDIT_PORTIN10,IDC_EDIT_PORTIN11,IDC_EDIT_PORTIN12,
        IDC_EDIT_PORTIN13,IDC_EDIT_PORTIN14,IDC_EDIT_PORTIN15,IDC_EDIT_PORTIN16,
        IDC_EDIT_PORTIN17,IDC_EDIT_PORTIN18,IDC_EDIT_PORTIN19,IDC_EDIT_PORTIN20,
        IDC_EDIT_PORTIN21,IDC_EDIT_PORTIN22,IDC_EDIT_PORTIN23,IDC_EDIT_PORTIN24,
        IDC_EDIT_PORTIN25,IDC_EDIT_PORTIN26,IDC_EDIT_PORTIN27,IDC_EDIT_PORTIN28,
        IDC_EDIT_PORTIN29,IDC_EDIT_PORTIN30,IDC_EDIT_PORTIN31,IDC_EDIT_PORTIN32
    };

    std::array<UINT, MAXCH> IDC_EDIT_PORTOUT = {
        IDC_EDIT_PORTOUT1,IDC_EDIT_PORTOUT2,IDC_EDIT_PORTOUT3,IDC_EDIT_PORTOUT4,
        IDC_EDIT_PORTOUT5,IDC_EDIT_PORTOUT6,IDC_EDIT_PORTOUT7,IDC_EDIT_PORTOUT8,
        IDC_EDIT_PORTOUT9,IDC_EDIT_PORTOUT10,IDC_EDIT_PORTOUT11,IDC_EDIT_PORTOUT12,
        IDC_EDIT_PORTOUT13,IDC_EDIT_PORTOUT14,IDC_EDIT_PORTOUT15,IDC_EDIT_PORTOUT16,
        IDC_EDIT_PORTOUT17,IDC_EDIT_PORTOUT18,IDC_EDIT_PORTOUT19,IDC_EDIT_PORTOUT20,
        IDC_EDIT_PORTOUT21,IDC_EDIT_PORTOUT22,IDC_EDIT_PORTOUT23,IDC_EDIT_PORTOUT24,
        IDC_EDIT_PORTOUT25,IDC_EDIT_PORTOUT26,IDC_EDIT_PORTOUT27,IDC_EDIT_PORTOUT28,
        IDC_EDIT_PORTOUT29,IDC_EDIT_PORTOUT30,IDC_EDIT_PORTOUT31,IDC_EDIT_PORTOUT32
    };

    std::array<UINT, MAXCH> IDC_EDIT_PORTNAME = {
        IDC_EDIT_PORTNAME1,IDC_EDIT_PORTNAME2,IDC_EDIT_PORTNAME3,IDC_EDIT_PORTNAME4,
        IDC_EDIT_PORTNAME5,IDC_EDIT_PORTNAME6,IDC_EDIT_PORTNAME7,IDC_EDIT_PORTNAME8,
        IDC_EDIT_PORTNAME9,IDC_EDIT_PORTNAME10,IDC_EDIT_PORTNAME11,IDC_EDIT_PORTNAME12,
        IDC_EDIT_PORTNAME13,IDC_EDIT_PORTNAME14,IDC_EDIT_PORTNAME15,IDC_EDIT_PORTNAME16,
        IDC_EDIT_PORTNAME17,IDC_EDIT_PORTNAME18,IDC_EDIT_PORTNAME19,IDC_EDIT_PORTNAME20,
        IDC_EDIT_PORTNAME21,IDC_EDIT_PORTNAME22,IDC_EDIT_PORTNAME23,IDC_EDIT_PORTNAME24,
        IDC_EDIT_PORTNAME25,IDC_EDIT_PORTNAME26,IDC_EDIT_PORTNAME27,IDC_EDIT_PORTNAME28,
        IDC_EDIT_PORTNAME29,IDC_EDIT_PORTNAME30,IDC_EDIT_PORTNAME31,IDC_EDIT_PORTNAME32
    };

    std::array<UINT, MAXCH> IDC_BTN_START = {
        IDC_BTN_START1,IDC_BTN_START2,IDC_BTN_START3,IDC_BTN_START4,
        IDC_BTN_START5,IDC_BTN_START6,IDC_BTN_START7,IDC_BTN_START8,
        IDC_BTN_START9,IDC_BTN_START10,IDC_BTN_START11,IDC_BTN_START12,
        IDC_BTN_START13,IDC_BTN_START14,IDC_BTN_START15,IDC_BTN_START16,
        IDC_BTN_START17,IDC_BTN_START18,IDC_BTN_START19,IDC_BTN_START20,
        IDC_BTN_START21,IDC_BTN_START22,IDC_BTN_START23,IDC_BTN_START24,
        IDC_BTN_START25,IDC_BTN_START26,IDC_BTN_START27,IDC_BTN_START28,
        IDC_BTN_START29,IDC_BTN_START30,IDC_BTN_START31,IDC_BTN_START32
	};

    std::array<UINT, MAXCH> IDC_BTN_STOP = {
        IDC_BTN_STOP1,IDC_BTN_STOP2,IDC_BTN_STOP3,IDC_BTN_STOP4,
        IDC_BTN_STOP5,IDC_BTN_STOP6,IDC_BTN_STOP7,IDC_BTN_STOP8,
        IDC_BTN_STOP9,IDC_BTN_STOP10,IDC_BTN_STOP11,IDC_BTN_STOP12,
        IDC_BTN_STOP13,IDC_BTN_STOP14,IDC_BTN_STOP15,IDC_BTN_STOP16,
        IDC_BTN_STOP17,IDC_BTN_STOP18,IDC_BTN_STOP19,IDC_BTN_STOP20,
        IDC_BTN_STOP21,IDC_BTN_STOP22,IDC_BTN_STOP23,IDC_BTN_STOP24,
        IDC_BTN_STOP25,IDC_BTN_STOP26,IDC_BTN_STOP27,IDC_BTN_STOP28,
        IDC_BTN_STOP29,IDC_BTN_STOP30,IDC_BTN_STOP31,IDC_BTN_STOP32
	};

    std::array<UINT, MAXCH> IDC_CHK = {
        IDC_CHK1,IDC_CHK2,IDC_CHK3,IDC_CHK4,
        IDC_CHK5,IDC_CHK6,IDC_CHK7,IDC_CHK8,
        IDC_CHK9,IDC_CHK10,IDC_CHK11,IDC_CHK12,
        IDC_CHK13,IDC_CHK14,IDC_CHK15,IDC_CHK16,
        IDC_CHK17,IDC_CHK18,IDC_CHK19,IDC_CHK20,
        IDC_CHK21,IDC_CHK22,IDC_CHK23,IDC_CHK24,
        IDC_CHK25,IDC_CHK26,IDC_CHK27,IDC_CHK28,
        IDC_CHK29,IDC_CHK30,IDC_CHK31,IDC_CHK32
	};
    std::array<UINT, MAXCH> IDC_CMB_BCFRASE={
		IDC_CMB_BCFRASE_1,IDC_CMB_BCFRASE_2,IDC_CMB_BCFRASE_3,IDC_CMB_BCFRASE_4,
		IDC_CMB_BCFRASE_5,IDC_CMB_BCFRASE_6,IDC_CMB_BCFRASE_7,IDC_CMB_BCFRASE_8,
		IDC_CMB_BCFRASE_9,IDC_CMB_BCFRASE_10,IDC_CMB_BCFRASE_11,IDC_CMB_BCFRASE_12,
		IDC_CMB_BCFRASE_13,IDC_CMB_BCFRASE_14,IDC_CMB_BCFRASE_15,IDC_CMB_BCFRASE_16,
		IDC_CMB_BCFRASE_17,IDC_CMB_BCFRASE_18,IDC_CMB_BCFRASE_19,IDC_CMB_BCFRASE_20,
		IDC_CMB_BCFRASE_21,IDC_CMB_BCFRASE_22,IDC_CMB_BCFRASE_23,IDC_CMB_BCFRASE_24,
		IDC_CMB_BCFRASE_25,IDC_CMB_BCFRASE_26,IDC_CMB_BCFRASE_27,IDC_CMB_BCFRASE_28,
		IDC_CMB_BCFRASE_29,IDC_CMB_BCFRASE_30,IDC_CMB_BCFRASE_31,IDC_CMB_BCFRASE_32
	};

    std::array<UINT, MAXCH> IDC_CMB_HLS = {
		IDC_CMB_HLS1, IDC_CMB_HLS2, IDC_CMB_HLS3, IDC_CMB_HLS4,
		IDC_CMB_HLS5, IDC_CMB_HLS6, IDC_CMB_HLS7, IDC_CMB_HLS8,
		IDC_CMB_HLS9, IDC_CMB_HLS10, IDC_CMB_HLS11, IDC_CMB_HLS12,
		IDC_CMB_HLS13, IDC_CMB_HLS14, IDC_CMB_HLS15, IDC_CMB_HLS16,
		IDC_CMB_HLS17, IDC_CMB_HLS18, IDC_CMB_HLS19, IDC_CMB_HLS20,
		IDC_CMB_HLS21, IDC_CMB_HLS22, IDC_CMB_HLS23, IDC_CMB_HLS24,
		IDC_CMB_HLS25, IDC_CMB_HLS26, IDC_CMB_HLS27, IDC_CMB_HLS28,
		IDC_CMB_HLS29, IDC_CMB_HLS30, IDC_CMB_HLS31, IDC_CMB_HLS32
	};

    std::array<UINT, MAXCH> IDC_ONAIR = {
		IDC_ONAIR_1,IDC_ONAIR_2,IDC_ONAIR_3,IDC_ONAIR_4,
		IDC_ONAIR_5,IDC_ONAIR_6,IDC_ONAIR_7,IDC_ONAIR_8,
		IDC_ONAIR_9,IDC_ONAIR_10,IDC_ONAIR_11,IDC_ONAIR_12,
		IDC_ONAIR_13,IDC_ONAIR_14,IDC_ONAIR_15,IDC_ONAIR_16,
		IDC_ONAIR_17,IDC_ONAIR_18,IDC_ONAIR_19,IDC_ONAIR_20,
		IDC_ONAIR_21,IDC_ONAIR_22,IDC_ONAIR_23,IDC_ONAIR_24,
		IDC_ONAIR_25,IDC_ONAIR_26,IDC_ONAIR_27,IDC_ONAIR_28,
		IDC_ONAIR_29,IDC_ONAIR_30,IDC_ONAIR_31,IDC_ONAIR_32
	};
	std::array<UINT, MAXCH> IDC_SRCIP = {
        IDC_SRCIP_1,IDC_SRCIP_2,IDC_SRCIP_3,IDC_SRCIP_4,
        IDC_SRCIP_5,IDC_SRCIP_6,IDC_SRCIP_7,IDC_SRCIP_8,
        IDC_SRCIP_9,IDC_SRCIP_10,IDC_SRCIP_11,IDC_SRCIP_12,
        IDC_SRCIP_13,IDC_SRCIP_14,IDC_SRCIP_15,IDC_SRCIP_16,
        IDC_SRCIP_17,IDC_SRCIP_18,IDC_SRCIP_19,IDC_SRCIP_20,
        IDC_SRCIP_21,IDC_SRCIP_22,IDC_SRCIP_23,IDC_SRCIP_24,
        IDC_SRCIP_25,IDC_SRCIP_26,IDC_SRCIP_27,IDC_SRCIP_28,
        IDC_SRCIP_29,IDC_SRCIP_30,IDC_SRCIP_31,IDC_SRCIP_32
	};
    std::array<UINT, MAXCH> IDC_BITRATE = {
        IDC_BITRATE_1,IDC_BITRATE_2,IDC_BITRATE_3,IDC_BITRATE_4,
        IDC_BITRATE_5,IDC_BITRATE_6,IDC_BITRATE_7,IDC_BITRATE_8,
        IDC_BITRATE_9,IDC_BITRATE_10,IDC_BITRATE_11,IDC_BITRATE_12,
        IDC_BITRATE_13,IDC_BITRATE_14,IDC_BITRATE_15,IDC_BITRATE_16,
        IDC_BITRATE_17,IDC_BITRATE_18,IDC_BITRATE_19,IDC_BITRATE_20,
        IDC_BITRATE_21,IDC_BITRATE_22,IDC_BITRATE_23,IDC_BITRATE_24,
        IDC_BITRATE_25,IDC_BITRATE_26,IDC_BITRATE_27,IDC_BITRATE_28,
        IDC_BITRATE_29,IDC_BITRATE_30,IDC_BITRATE_31,IDC_BITRATE_32
	};
    std::array<UINT, MAXCH> IDC_BTN_START_TEST = {
        IDC_BTN_START_TEST1,IDC_BTN_START_TEST2,IDC_BTN_START_TEST3,IDC_BTN_START_TEST4,
        IDC_BTN_START_TEST5,IDC_BTN_START_TEST6,IDC_BTN_START_TEST7,IDC_BTN_START_TEST8,
        IDC_BTN_START_TEST9,IDC_BTN_START_TEST10,IDC_BTN_START_TEST11,IDC_BTN_START_TEST12,
        IDC_BTN_START_TEST13,IDC_BTN_START_TEST14,IDC_BTN_START_TEST15,IDC_BTN_START_TEST16,
        IDC_BTN_START_TEST17,IDC_BTN_START_TEST18,IDC_BTN_START_TEST19,IDC_BTN_START_TEST20,
        IDC_BTN_START_TEST21,IDC_BTN_START_TEST22,IDC_BTN_START_TEST23,IDC_BTN_START_TEST24,
        IDC_BTN_START_TEST25,IDC_BTN_START_TEST26,IDC_BTN_START_TEST27,IDC_BTN_START_TEST28,
        IDC_BTN_START_TEST29,IDC_BTN_START_TEST30,IDC_BTN_START_TEST31,IDC_BTN_START_TEST32
    };
    /*
    std::array<std::wstring, MAXCH> _DEF_HLS = {
        L"hls",L"hls",L"hls",L"hls",
		L"hls",L"hls",L"hls",L"hls",
		L"hls",L"hls",L"hls",L"hls",
		L"hls",L"hls",L"hls",L"hls",
		L"hls",L"hls",L"hls",L"hls",
		L"hls",L"hls",L"hls",L"hls",
		L"hls",L"hls",L"hls",L"hls",
		L"hls",L"hls",L"hls",L"hls"
    };
*/

    std::array<UINT, MAXCH> _DEF_PORTIN = {
		5004,5006,5008,5010,
        5012,5014,5016,5018,
        5020,5022,5024,5026,
        5028,5030,5032,5034,
        5036,5038,5040,5042,
        5044,5046,5048,5050,
        5052,5054,5056,5058,
		5060,5062,5064,5066
	};
    std::array<UINT, MAXCH> _DEF_PORTOUT = {
        8554,8556,8558,8560,
		8562,8564,8566,8568,
		8570,8572,8574,8576,
		8578,8580,8582,8584,
		8586,8588,8590,8592,
		8594,8596,8598,8600,
		8602,8604,8606,8608,
		8610,8612,8614,8616
    };

    UINT HTTP_PORT = 8080;                        // HTTPポート（HLS用）
    std::wstring HLS_STR = L"hls";
};
/////////////////////////////////////////
//
// ヘルパー関数
//
////////////////////////////////////////
std::wstring GetIniPath();
//void SaveSettings(HWND hDlg);
void SaveSettings(HWND hDlg, UINT _IDC_EDIT_PORTIN, UINT _IDC_EDIT_PORTOUT, UINT _IDC_EDIT_PORTNAME);
void SaveSettings(HWND hDlg,APP_SETTINGS& _GAPP);

void LoadSettings(HWND hDlg, UINT _IDC_EDIT_PORTIN, UINT _IDC_EDIT_PORTOUT, UINT _IDC_EDIT_PORTNAME);
void LoadSettings(HWND hDlg,APP_SETTINGS& _GAPP);

//void SetRunningUi(HWND hDlg, bool running);
void SetRunningUi(HWND hDlg, bool running,
    UINT _IDC_BTN_START,
    UINT _IDC_BTN_STOP,
    UINT _IDC_EDIT_PORTIN,
    UINT _IDC_EDIT_PORTOUT,
    UINT _IDC_EDIT_PORTNAME
);
void SetRunningUi(HWND hDlg, bool running,APP_SETTINGS& _GAPP);

void ForceWindowOnVisibleMonitor(HWND hWnd);

//void LoadSettings(
//    HWND hDlg,
//    APP_SETTINGS& _GAPP
//);
//void SaveSettings(
//    HWND hDlg,
//    UINT _IDC_EDIT_PORTIN,
//    UINT _IDC_EDIT_PORTOUT,
//    UINT _IDC_EDIT_PORTNAME
//);
//void SetRunningUi(HWND hDlg, bool running,
//    APP_SETTINGS& _GAPP
//);
