#pragma once

#include "resource.h"

#define MAXCH 32

struct _GMainLoop;
typedef struct _GMainLoop GMainLoop;

class RtspServerController
{
public:
    RTSPCtrl        rCtrl; //GMainLoopを含む 

    RtspServerController();
    ~RtspServerController();

    bool Start(int inPort, int outPort, const std::string& channelUtf8, HWND hwndNotify);
    //bool StartEx(int inPort, int outPort, int _ch, const std::string& channelUtf8, HWND hwndNotify);
	bool StartExx(HWND hwndNotify); //rCtrlの内容を使う版

    void Stop();
    bool IsRunning() const { return running_.load(); }

private:
    void ThreadMain(int inPort, int outPort, std::string channelUtf8);
    //void ThreadMainEx(int inPort, int outPort, std::string channelUtf8);

    void ThreadMainExx();

    //void ThreadMain(GST_RTSP_SVPARAMS& _gsrv, std::string channelUtf8);
    //void ThreadMainGsrv(GST_RTSP_SVPARAMS& _gsrv);

private:
    std::atomic<bool> running_{ false };
    std::thread       th_;
    //GMainLoop*        loop_{ nullptr };
    HWND              hwndNotify_{ nullptr };

};


std::string WideToUtf8(const std::wstring& ws);
bool GetIntFromEdit(HWND hDlg, int id, int& outValue);

///////////////////////////////////////////////
// 
// 設定関連の定数・構造体
//
///////////////////////////////////////////////
struct APP_SETTINGS
{
	int size = MAXCH; // チャンネル数
    std::array<std::wstring, MAXCH> SVNAME = {
    L"CH01",L"CH02",L"CH03",L"CH04",L"CH05",L"CH06",L"CH07",L"CH08",
    L"CH09",L"CH10",L"CH11",L"CH12",L"CH13",L"CH14",L"CH15",L"CH16",
    L"CH17",L"CH18",L"CH19",L"CH20",L"CH21",L"CH22",L"CH23",L"CH24",
    L"CH25",L"CH26",L"CH27",L"CH28",L"CH29",L"CH30",L"CH31",L"CH32"
    };

    std::array<UINT, MAXCH> IDC_EDIT_PORTIN = {
        IDC_EDIT_PORTIN1,IDC_EDIT_PORTIN2,IDC_EDIT_PORTIN3,IDC_EDIT_PORTIN4,
        IDC_EDIT_PORTIN5,IDC_EDIT_PORTIN6,IDC_EDIT_PORTIN7,IDC_EDIT_PORTIN8,
        IDC_EDIT_PORTIN9,IDC_EDIT_PORTIN10,IDC_EDIT_PORTIN11,IDC_EDIT_PORTIN12,
        IDC_EDIT_PORTIN13,IDC_EDIT_PORTIN14,IDC_EDIT_PORTIN15,IDC_EDIT_PORTIN16,
        IDC_EDIT_PORTIN17,IDC_EDIT_PORTIN18,IDC_EDIT_PORTIN19,IDC_EDIT_PORTIN20,
        IDC_EDIT_PORTIN21,IDC_EDIT_PORTIN22,IDC_EDIT_PORTIN23,IDC_EDIT_PORTIN24,
        IDC_EDIT_PORTIN25,IDC_EDIT_PORTIN26,IDC_EDIT_PORTIN27,IDC_EDIT_PORTIN28,
        IDC_EDIT_PORTIN29,IDC_EDIT_PORTIN30,IDC_EDIT_PORTIN31,IDC_EDIT_PORTIN32
    };

    std::array<UINT, MAXCH> IDC_EDIT_PORTOUT = {
        IDC_EDIT_PORTOUT1,IDC_EDIT_PORTOUT2,IDC_EDIT_PORTOUT3,IDC_EDIT_PORTOUT4,
        IDC_EDIT_PORTOUT5,IDC_EDIT_PORTOUT6,IDC_EDIT_PORTOUT7,IDC_EDIT_PORTOUT8,
        IDC_EDIT_PORTOUT9,IDC_EDIT_PORTOUT10,IDC_EDIT_PORTOUT11,IDC_EDIT_PORTOUT12,
        IDC_EDIT_PORTOUT13,IDC_EDIT_PORTOUT14,IDC_EDIT_PORTOUT15,IDC_EDIT_PORTOUT16,
        IDC_EDIT_PORTOUT17,IDC_EDIT_PORTOUT18,IDC_EDIT_PORTOUT19,IDC_EDIT_PORTOUT20,
        IDC_EDIT_PORTOUT21,IDC_EDIT_PORTOUT22,IDC_EDIT_PORTOUT23,IDC_EDIT_PORTOUT24,
        IDC_EDIT_PORTOUT25,IDC_EDIT_PORTOUT26,IDC_EDIT_PORTOUT27,IDC_EDIT_PORTOUT28,
        IDC_EDIT_PORTOUT29,IDC_EDIT_PORTOUT30,IDC_EDIT_PORTOUT31,IDC_EDIT_PORTOUT32
    };

    std::array<UINT, MAXCH> IDC_EDIT_PORTNAME = {
        IDC_EDIT_PORTNAME1,IDC_EDIT_PORTNAME2,IDC_EDIT_PORTNAME3,IDC_EDIT_PORTNAME4,
        IDC_EDIT_PORTNAME5,IDC_EDIT_PORTNAME6,IDC_EDIT_PORTNAME7,IDC_EDIT_PORTNAME8,
        IDC_EDIT_PORTNAME9,IDC_EDIT_PORTNAME10,IDC_EDIT_PORTNAME11,IDC_EDIT_PORTNAME12,
        IDC_EDIT_PORTNAME13,IDC_EDIT_PORTNAME14,IDC_EDIT_PORTNAME15,IDC_EDIT_PORTNAME16,
        IDC_EDIT_PORTNAME17,IDC_EDIT_PORTNAME18,IDC_EDIT_PORTNAME19,IDC_EDIT_PORTNAME20,
        IDC_EDIT_PORTNAME21,IDC_EDIT_PORTNAME22,IDC_EDIT_PORTNAME23,IDC_EDIT_PORTNAME24,
        IDC_EDIT_PORTNAME25,IDC_EDIT_PORTNAME26,IDC_EDIT_PORTNAME27,IDC_EDIT_PORTNAME28,
        IDC_EDIT_PORTNAME29,IDC_EDIT_PORTNAME30,IDC_EDIT_PORTNAME31,IDC_EDIT_PORTNAME32
    };

    std::array<UINT, MAXCH> IDC_BTN_START = {
        IDC_BTN_START1,IDC_BTN_START2,IDC_BTN_START3,IDC_BTN_START4,
        IDC_BTN_START5,IDC_BTN_START6,IDC_BTN_START7,IDC_BTN_START8,
        IDC_BTN_START9,IDC_BTN_START10,IDC_BTN_START11,IDC_BTN_START12,
        IDC_BTN_START13,IDC_BTN_START14,IDC_BTN_START15,IDC_BTN_START16,
        IDC_BTN_START17,IDC_BTN_START18,IDC_BTN_START19,IDC_BTN_START20,
        IDC_BTN_START21,IDC_BTN_START22,IDC_BTN_START23,IDC_BTN_START24,
        IDC_BTN_START25,IDC_BTN_START26,IDC_BTN_START27,IDC_BTN_START28,
        IDC_BTN_START29,IDC_BTN_START30,IDC_BTN_START31,IDC_BTN_START32
	};

    std::array<UINT, MAXCH> IDC_BTN_STOP = {
        IDC_BTN_STOP1,IDC_BTN_STOP2,IDC_BTN_STOP3,IDC_BTN_STOP4,
        IDC_BTN_STOP5,IDC_BTN_STOP6,IDC_BTN_STOP7,IDC_BTN_STOP8,
        IDC_BTN_STOP9,IDC_BTN_STOP10,IDC_BTN_STOP11,IDC_BTN_STOP12,
        IDC_BTN_STOP13,IDC_BTN_STOP14,IDC_BTN_STOP15,IDC_BTN_STOP16,
        IDC_BTN_STOP17,IDC_BTN_STOP18,IDC_BTN_STOP19,IDC_BTN_STOP20,
        IDC_BTN_STOP21,IDC_BTN_STOP22,IDC_BTN_STOP23,IDC_BTN_STOP24,
        IDC_BTN_STOP25,IDC_BTN_STOP26,IDC_BTN_STOP27,IDC_BTN_STOP28,
        IDC_BTN_STOP29,IDC_BTN_STOP30,IDC_BTN_STOP31,IDC_BTN_STOP32
	};

    std::array<UINT, MAXCH> IDC_CHK = {
        IDC_CHK1,IDC_CHK2,IDC_CHK3,IDC_CHK4,
        IDC_CHK5,IDC_CHK6,IDC_CHK7,IDC_CHK8,
        IDC_CHK9,IDC_CHK10,IDC_CHK11,IDC_CHK12,
        IDC_CHK13,IDC_CHK14,IDC_CHK15,IDC_CHK16,
        IDC_CHK17,IDC_CHK18,IDC_CHK19,IDC_CHK20,
        IDC_CHK21,IDC_CHK22,IDC_CHK23,IDC_CHK24,
        IDC_CHK25,IDC_CHK26,IDC_CHK27,IDC_CHK28,
        IDC_CHK29,IDC_CHK30,IDC_CHK31,IDC_CHK32
	};

    std::array<UINT, MAXCH> _DEF_PORTIN = {
		5004,5007,5009,5010,
        5011,5012,5013,5014,
        5015,5016,5017,5018,
        5019,5020,5021,5022,
        5023,5024,5025,5026,
        5027,5028,5029,5030,
        5031,5032,5033,5034,
        5035,5036,5037,5038
    };
    std::array<UINT, MAXCH> _DEF_PORTOUT = {
        8554,8555,8556,8557,
        8558,8559,8560,8561,
        8562,8563,8564,8565,
        8566,8567,8568,8569,
        8570,8571,8572,8573,
        8574,8575,8576,8577,
        8578,8579,8580,8581,
        8582,8583,8584,8585
    };
};
/////////////////////////////////////////
//
// ヘルパー関数
//
////////////////////////////////////////
std::wstring GetIniPath();
//void SaveSettings(HWND hDlg);
void SaveSettings(HWND hDlg, UINT _IDC_EDIT_PORTIN, UINT _IDC_EDIT_PORTOUT, UINT _IDC_EDIT_PORTNAME);
void SaveSettings(HWND hDlg,APP_SETTINGS& _GAPP);

void LoadSettings(HWND hDlg, UINT _IDC_EDIT_PORTIN, UINT _IDC_EDIT_PORTOUT, UINT _IDC_EDIT_PORTNAME);
void LoadSettings(HWND hDlg,APP_SETTINGS& _GAPP);

//void SetRunningUi(HWND hDlg, bool running);
void SetRunningUi(HWND hDlg, bool running,
    UINT _IDC_BTN_START,
    UINT _IDC_BTN_STOP,
    UINT _IDC_EDIT_PORTIN,
    UINT _IDC_EDIT_PORTOUT,
    UINT _IDC_EDIT_PORTNAME
);
void SetRunningUi(HWND hDlg, bool running,APP_SETTINGS& _GAPP);

//void LoadSettings(
//    HWND hDlg,
//    APP_SETTINGS& _GAPP
//);
//void SaveSettings(
//    HWND hDlg,
//    UINT _IDC_EDIT_PORTIN,
//    UINT _IDC_EDIT_PORTOUT,
//    UINT _IDC_EDIT_PORTNAME
//);
//void SetRunningUi(HWND hDlg, bool running,
//    APP_SETTINGS& _GAPP
//);
